config: g1_basic_ctrl_hardware
onboard:
  control:
    - pkg: sample_contact_walking
      executable: basic_torque_control
      params:
        num_ctrl_joints: 27
        log_file_name: "mpc_logs/basic_torque_control_log.csv"
        # log_file_name: "mpc_logs/basic_torque_control_log_hardware.csv"
        torque_scalar: 5.
# --------- Control Params --------- #
        # Note: Right now this will only be used on hardware and NOT in the sim!
        ctrl_joint_names: ["left_hip_pitch_joint",
            "left_hip_roll_joint",
            "left_hip_yaw_joint",
            "left_knee_joint",
            "left_ankle_pitch_joint",
            "left_ankle_roll_joint",
            "right_hip_pitch_joint",
            "right_hip_roll_joint",
            "right_hip_yaw_joint",
            "right_knee_joint",
            "right_ankle_pitch_joint",
            "right_ankle_roll_joint",
            "waist_yaw_joint",
            # "waist_roll_joint",
            # "waist_pitch_joint",
            "left_shoulder_pitch_joint",
            "left_shoulder_roll_joint",
            "left_shoulder_yaw_joint",
            "left_elbow_joint",
            "left_wrist_roll_joint",
            "left_wrist_pitch_joint",
            "left_wrist_yaw_joint",
            "right_shoulder_pitch_joint",
            "right_shoulder_roll_joint",
            "right_shoulder_yaw_joint",
            "right_elbow_joint",
            "right_wrist_roll_joint",
            "right_wrist_pitch_joint",
            "right_wrist_yaw_joint",]
        kp: [0., 0., 0., 0., 0., 0.,
             0., 0., 0., 0., 0., 0.,
             0.,
             0., 0., 0., 0., 0., 0., 0.,
             0., 0., 0., 0., 0., 0., 0.,]
          # [240., 260, 220, 270, 200, 40,
          #    240., 260, 220, 270, 200, 40,
          #    40,
          #    100, 100, 100, 100, 40, 40, 40,
          #    100, 100, 100, 100, 40, 40, 40]
        kd: [0., 0., 0., 0., 0., 0.,
             0., 0., 0., 0., 0., 0.,
             0.,
             0., 0., 0., 0., 0., 0., 0.,
             0., 0., 0., 0., 0., 0., 0.,]
        # [4., 4, 4, 4, 4, 2,
        #      4, 4, 4, 4, 4, 2,
        #      2,
        #      2, 2, 2, 2, 5, 5, 5,
        #      2, 2, 2, 2, 5, 5, 5,]
# ---------- Step Planner ---------- #
        foot_offsets: [0.025, 0.1164, 0.025, 0.1164, 0.025, -0.1164, 0.025, -0.1164]  # Making the offsets the same so the feet are always projected to the same place
      publishers:
        # Low level controller publisher
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/g1/low_level_control
          history_depth: 10
      subscribers:
        # Estimated state subscriber
        - ros_parameter: sub_est_setting
          topic: /obelisk/g1/est_state # est_state, target_state
          history_depth: 10
        # ----- Joystick subscriber ----- #
        - ros_parameter: joystick_sub_setting
          topic: /obelisk/g1/joy
      timers:
        # Low level control timer
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 0.001
 # ----------------------------------------------- #
 # ----- High Level/Execution FSM Controller ----- #
 # ----------------------------------------------- #
    - pkg: obelisk_unitree_cpp
      executable: obelisk_unitree_joystick
      # callback_groups:
      params:
        low_level_ctrl_button: 4    # Enter low level control mode with the LEFT_BUMPER
        high_level_ctrl_button: 5   # Enter high level control mode with the RIGHT_BUMPER
        # Other controls: Damping on right DPAD, Home on left DPAD, user pose at squares
      publishers:
      # ----- Execution FSM ----- #
        - ros_parameter: pub_exec_fsm_setting
          topic: /obelisk/g1/exec_fsm
          history_depth: 10
          callback_group: None
      # ----- High Level Control ----- #
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/g1/high_level_ctrl
          history_depth: 10
          callback_group: None
      subscribers:
      # ----- Joystick subscriber ----- #
        - ros_parameter: sub_est_setting
          topic: /obelisk/g1/joy
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 100  # Control callback is not being used
          callback_group: None
  estimation:
 # ----------------------------------------------- #
 # ------------------ Estimator ------------------ #
 # ----------------------------------------------- #
    - pkg: sample_contact_walking
      executable: state_estimator
      params:
        mpc_settings_path:  /home/zolkin/sample-contact-walking/sample_contact_walking/configs/g1_mpc_config.yaml
        urdf_path: /home/zolkin/sample-contact-walking/g1_model/urdf/g1_hand.urdf
        robot_name: "g1"
        base_link_name: "pelvis"
        use_sim_state: false #true
        use_torso_mocap: true #false
        pelvis_ang_vel_lpf_coefs: [0.05, 0.15, 0.8] # TODO: Tune these
      callback_groups:
        debug_cbg: MutuallyExclusiveCallbackGroup 
      publishers:
        - ros_parameter: pub_est_setting
          topic: /obelisk/g1/est_state
          history_depth: 10
          callback_group: None
          non_obelisk: False
      timers:
        - ros_parameter: timer_est_setting
          timer_period_sec: 0.001
          callback_group: None
      subscribers:
      # ---------- Joint Encoders ---------- #
        - ros_parameter: joint_encoders_setting
          topic: /obelisk/g1/joint_encoders
          history_depth: 10
          callback_group: None
      # ---------- Pelvis Mocap ---------- #
        - ros_parameter: mocap_setting
          topic: /obelisk/g1/pelvis_pose
          history_depth: 10
          callback_group: None
      # ---------- Torso Mocap ---------- #
        - ros_parameter: torso_mocap_setting
          # topic: G1_torso/pose
          topic: /obelisk/g1/torso_pose
          history_depth: 10
          callback_group: None
      # ---------- Torso IMU ---------- #
        - ros_parameter: torso_imu_setting
          topic: /obelisk/g1/torso_imu
          history_depth: 10
          callback_group: None
      # ---------- Pelvis IMU ---------- #
        - ros_parameter: pelvis_imu_setting
          topic: /obelisk/g1/pelvis_imu
          history_depth: 10
          callback_group: None
      # ---------- True Sim State ---------- #
        - ros_parameter: true_sim_sub_setting
          topic: /obelisk/g1/true_sim_state
          history_depth: 10
          callback_group: None
  # sensing:
  robot:
    # - is_simulated: False
    #   pkg: obelisk_unitree_cpp
    #   executable: obelisk_unitree_g1_hardware
    #   params:
    #     network_interface_name: enp4s0
    #     default_kp: [
    #                 10., 10., 10.,    # L hip
    #                 10., 10., 10.,    # L knee, ankle
    #                 10., 10., 10.,    # R hip
    #                 10., 10., 10.,    # R knee, ankle
    #                 10., #10., 10.,    # Waist
    #                 5., 5., 5.,       # L shoulder
    #                 5., 5., 5., 5.,   # L elbow, wrist
    #                 5., 5., 5.,       # R shoulder
    #                 5., 5., 5., 5.,   # R elbow, wrist
    #                 ]
    #     default_kd: [
    #                 1., 1., 1.,       # L hip
    #                 1., 1., 1.,       # L knee, ankle
    #                 1., 1., 1.,       # R hip
    #                 1., 1., 1.,       # R knee, ankle
    #                 1., #1., 1.,       # Waist
    #                 1., 1., 1.,       # L shoulder
    #                 1., 1., 1., 1.,   # L elbow, wrist
    #                 1., 1., 1.,       # R shoulder
    #                 1., 1., 1., 1.,   # R elbow, wrist
    #     ]
    - is_simulated: True
      pkg: sample_contact_walking
      executable: simulation
      params:
        ic_keyframe: standing
      # callback_groups:
      publishers:
        # ----- Joints ----- #
        - ros_parameter: pub_sensor_setting
          topic: /obelisk/g1/joint_encoders
          history_depth: 10
        # ----- IMU ----- #
        - ros_parameter: pub_imu_setting
          topic: /obelisk/g1/pelvis_imu
          history_depth: 10
        # ----- Odom ----- #
        - ros_parameter: pub_odom_setting
          topic: /obelisk/g1/odom
          history_depth: 10
      timers:
        - ros_parameter: timer_sensor_setting
          timer_period_sec: 0.02  # TODO: Tune the timing (?)
          callback_group: None
      subscribers:
      # ----- Control ----- #
        - ros_parameter: sub_ctrl_setting
          topic: /obelisk/g1/low_level_control
          history_depth: 10
          callback_group: None
      # ----- Execution FSM ----- #
        - ros_parameter: sub_fsm_setting
          topic: /obelisk/g1/exec_fsm
          history_depth: 10
          callback_group: None
      # ----- High Level Control ----- #
        - ros_parameter: sub_high_level_ctrl_setting
          topic: /obelisk/g1/high_level_ctrl
          history_depth: 10
          callback_group: None
      sim:
        - ros_parameter: mujoco_setting
          robot_pkg: g1_model
          # model_xml_path: g1_29dof_with_hand_fixed_base.xml
          model_xml_path: g1_27dof_fixed_base.xml
          # model_xml_path: basic_scene.xml
          num_steps_per_viz: 32 #16 # No longer used
          sensor_settings:
          # ---------- Joint Encoders ---------- #
          - topic: /obelisk/g1/joint_encoders
            dt: 0.001
            msg_type: ObkJointEncoders
            sensor_names:
            # ---------- Joint Positions ---------- #
              left_hip_pitch_joint_pos_sensor: jointpos
              left_hip_roll_joint_pos_sensor: jointpos
              left_hip_yaw_joint_pos_sensor: jointpos
              left_knee_joint_pos_sensor: jointpos
              left_ankle_pitch_joint_pos_sensor: jointpos
              left_ankle_roll_joint_pos_sensor: jointpos

              right_hip_pitch_joint_pos_sensor: jointpos
              right_hip_roll_joint_pos_sensor: jointpos
              right_hip_yaw_joint_pos_sensor: jointpos
              right_knee_joint_pos_sensor: jointpos
              right_ankle_pitch_joint_pos_sensor: jointpos
              right_ankle_roll_joint_pos_sensor: jointpos

              waist_yaw_joint_pos_sensor: jointpos
              # waist_roll_joint_pos_sensor: jointpos
              # waist_pitch_joint_pos_sensor: jointpos

              left_shoulder_pitch_joint_pos_sensor: jointpos
              left_shoulder_roll_joint_pos_sensor: jointpos
              left_shoulder_yaw_joint_pos_sensor: jointpos
              left_elbow_joint_pos_sensor: jointpos
              left_wrist_roll_joint_pos_sensor: jointpos
              left_wrist_pitch_joint_pos_sensor: jointpos
              left_wrist_yaw_joint_pos_sensor: jointpos

              # left_hand_thumb_0_joint_pos_sensor: jointpos
              # left_hand_thumb_1_joint_pos_sensor: jointpos
              # left_hand_thumb_2_joint_pos_sensor: jointpos
              # left_hand_middle_0_joint_pos_sensor: jointpos
              # left_hand_middle_1_joint_pos_sensor: jointpos
              # left_hand_index_0_joint_pos_sensor: jointpos
              # left_hand_index_1_joint_pos_sensor: jointpos

              right_shoulder_pitch_joint_pos_sensor: jointpos
              right_shoulder_roll_joint_pos_sensor: jointpos
              right_shoulder_yaw_joint_pos_sensor: jointpos
              right_elbow_joint_pos_sensor: jointpos
              right_wrist_roll_joint_pos_sensor: jointpos
              right_wrist_pitch_joint_pos_sensor: jointpos
              right_wrist_yaw_joint_pos_sensor: jointpos

              # right_hand_thumb_0_joint_pos_sensor: jointpos
              # right_hand_thumb_1_joint_pos_sensor: jointpos
              # right_hand_thumb_2_joint_pos_sensor: jointpos
              # right_hand_middle_0_joint_pos_sensor: jointpos
              # right_hand_middle_1_joint_pos_sensor: jointpos
              # right_hand_index_0_joint_pos_sensor: jointpos
              # right_hand_index_1_joint_pos_sensor: jointpos
            # ---------- Joint Velocities ---------- #
              left_hip_pitch_joint_vel_sensor: jointvel
              left_hip_roll_joint_vel_sensor: jointvel
              left_hip_yaw_joint_vel_sensor: jointvel
              left_knee_joint_vel_sensor: jointvel
              left_ankle_pitch_joint_vel_sensor: jointvel
              left_ankle_roll_joint_vel_sensor: jointvel

              right_hip_pitch_joint_vel_sensor: jointvel
              right_hip_roll_joint_vel_sensor: jointvel
              right_hip_yaw_joint_vel_sensor: jointvel
              right_knee_joint_vel_sensor: jointvel
              right_ankle_pitch_joint_vel_sensor: jointvel
              right_ankle_roll_joint_vel_sensor: jointvel

              waist_yaw_joint_vel_sensor: jointvel
              # waist_roll_joint_vel_sensor: jointvel
              # waist_pitch_joint_vel_sensor: jointvel

              left_shoulder_pitch_joint_vel_sensor: jointvel
              left_shoulder_roll_joint_vel_sensor: jointvel
              left_shoulder_yaw_joint_vel_sensor: jointvel
              left_elbow_joint_vel_sensor: jointvel
              left_wrist_roll_joint_vel_sensor: jointvel
              left_wrist_pitch_joint_vel_sensor: jointvel
              left_wrist_yaw_joint_vel_sensor: jointvel

              # left_hand_thumb_0_joint_vel_sensor: jointvel
              # left_hand_thumb_1_joint_vel_sensor: jointvel
              # left_hand_thumb_2_joint_vel_sensor: jointvel
              # left_hand_middle_0_joint_vel_sensor: jointvel
              # left_hand_middle_1_joint_vel_sensor: jointvel
              # left_hand_index_0_joint_vel_sensor: jointvel
              # left_hand_index_1_joint_vel_sensor: jointvel

              right_shoulder_pitch_joint_vel_sensor: jointvel
              right_shoulder_roll_joint_vel_sensor: jointvel
              right_shoulder_yaw_joint_vel_sensor: jointvel
              right_elbow_joint_vel_sensor: jointvel
              right_wrist_roll_joint_vel_sensor: jointvel
              right_wrist_pitch_joint_vel_sensor: jointvel
              right_wrist_yaw_joint_vel_sensor: jointvel

              # right_hand_thumb_0_joint_vel_sensor: jointvel
              # right_hand_thumb_1_joint_vel_sensor: jointvel
              # right_hand_thumb_2_joint_vel_sensor: jointvel
              # right_hand_middle_0_joint_vel_sensor: jointvel
              # right_hand_middle_1_joint_vel_sensor: jointvel
              # right_hand_index_0_joint_vel_sensor: jointvel
              # right_hand_index_1_joint_vel_sensor: jointvel
          # ---------- Torso IMU ---------- #
          - topic: /obelisk/g1/torso_imu
            dt: 0.001
            msg_type: ObkImu
            sensor_names:
              torso_imu_acc_sensor: accelerometer
              torso_imu_gyro_sensor: gyro
              torso_imu_quat_sensor: framequat
          # ---------- Pelvis IMU ---------- #
          - topic: /obelisk/g1/pelvis_imu
            dt: 0.001
            msg_type: ObkImu
            sensor_names:
              pelvis_imu_acc_sensor: accelerometer
              pelvis_imu_gyro_sensor: gyro
              pelvis_imu_quat_sensor: framequat
          # ---------- Pelvis Mocap ---------- #
          - topic: /obelisk/g1/pelvis_pose
            dt: 0.002   # 500 Hz
            msg_type: PoseStamped
            sensor_names:
              base_mocap_pos_sensor: framepos
              base_mocap_quat_sensor: framequat
          # ---------- Torso Mocap ---------- #
          - topic: /obelisk/g1/torso_pose
            dt: 0.002   # 500 Hz
            msg_type: PoseStamped
            sensor_names:
              torso_mocap_pos_sensor: framepos
              torso_mocap_quat_sensor: framequat
          # viz_geoms:
          #   dt: 1
          #   # ----- Stair scene ----- #
          #   # stair_1: box
          #   # stair_2: box
          #   # stair_3: box
          #   # ----- Tile scene ----- #
          #   tile1: box
          #   tile2: box
          #   tile3: box
          #   tile4: box
          #   tile5: box
          #   tile6: box
          #   tile7: box
          #   tile8: box
          #   tile9: box
  viz:
    on: True
    viz_tool: foxglove
    rviz_pkg: obelisk_ros
    rviz_config: basic_obk_config.rviz
    viz_nodes:
      - pkg: obelisk_viz_cpp
        executable: default_robot_viz
        robot_pkg: g1_model
        urdf: g1_viz.urdf
        robot_topic: robot_description
        subscribers:
          - ros_parameter: sub_viz_est_setting
            topic: /obelisk/g1/est_state
            history_depth: 10
            callback_group: None
            non_obelisk: False
        publishers:
          - ros_parameter: pub_viz_joint_setting
            topic: joint_states
            history_depth: 10
            callback_group: None
        timers:
          - ros_parameter: timer_viz_joint_setting
            timer_period_sec: 0.01
            callback_group: None
  joystick:
    on: True
    pub_topic: /obelisk/g1/joy
    sub_topic: /obelisk/g1/joy_feedback