general_settings:
  nodes: 32
  verbose: True #True
  node_dt_type: two_groups # Even, two_groups, Adaptive
  node_group_1_n: 5
  node_group_2_n: 27
  node_dt_1: 0.015
  node_dt_2: 0.025
  compile_derivatives: False #True
  base_frame: "pelvis"
  scale_cost: False
  max_initial_solves: 20
  initial_constraint_tol: 5e-4
  nodes_full_dynamics: 10 #4 #15 #3 #4   # TODO: Why does it get worse with less full dynamics? Seems likea frame issue
  delay_prediction_dt: 0
  terminal_cost_weight: 20 #10 #2 #2 #10
solver_settings:
# HPIPM:
# Some note: 
# - Having a lower barrier seems to help significantly
# - For robust with lots of iterations I need pred_corr turned off, but when I have balance with even moderate iterations (15) it can (and should) be on
# - mu0 around 1-5 seems best for the timing I'm looking at
# - Even with balance, too many iterations causes issues
  mode: Balance #Robust #Speed #Robust #Balance -- To get a success the best chance is with Robust and give more iterations
  alpha_min: 1e-8
  max_iter: 10 #8 #10 #7 #10 #30 #7 #8 # With 30 and robust I am having a ahrd time getting it to work
  mu0: 10 #5 #1 #100
  tol_stat: 1e-8
  tol_eq: 1e-8
  tol_comp: 1e-8
  tol_ineq: 1e-8
  reg_prim: 1e-12 #1e-12
  warm_start: 0 #0
  pred_corr: 1 # I thought turning this off was critical, but maybe not (?)
  ric_alg: 1
  split_step: 0 #1 #0
  # No Sim decent preformance: Speed, 10 iters, mu0: 1
# OSQP
  # rel_tol: 1e-3
  # abs_tol: 1e-3
  # verbose: False
  # polish: False
  # rho: 0.01
  # alpha: 1.6 # 1.6, 1.1
  # sigma: 1e-6
  # adaptive_rho: False
  # max_iter: 20 #50 #50 #20 Increasing this definetly helps 40-60 seems like a good balance
  # scaling: 10 # Solve gets faster as scaling goes down, but also the quality gets worse. There is a balance
constraints:
  friction_coef: 0.5 #0.6 #0.7  # TODO: Tune this
  friction_margin: 2
  max_grf: 800 #500 #8000
  collisions:
    - frame1: "left_toe"
      frame2: "right_toe"
      radius1: 0.1 #0.13
      radius2: 0.1 #0.13
    - frame1: "left_heel"
      frame2: "right_heel"
      radius1: 0.1 #0.13
      radius2: 0.1 #0.13
    - frame1: "left_toe"
      frame2: "right_heel"
      radius1: 0.07
      radius2: 0.07
    - frame1: "left_heel"
      frame2: "right_toe"
      radius1: 0.07
      radius2: 0.07
    - frame1: "left_wrist_yaw_link"
      frame2: "waist_support_link"
      radius1: 0.06
      radius2: 0.06
    - frame1: "right_wrist_yaw_link"
      frame2: "waist_support_link"
      radius1: 0.06
      radius2: 0.06
  swing_start_node: 1 #2
  swing_end_node: 32
  holonomic_start_node: 1 
  holonomic_end_node: 31
  collision_start_node: 2
  collision_end_node: 32
  polytope_start_node: 2
  polytope_end_node: 32
costs:
# NOTE: The resulting behaviour is suprisingly sensitive
  - type: ConfigurationTracking
    name: "ConfigTracking"
    weight:  [3, 3, 100, #2, 2, 5,  #15, 
              # 4, 4, 4,
              2, 2, 2,
              0.05, 1, 2, 0.01, 1, #1,         # Left Leg
              0.05, 1, 2, 0.01, 1, #1,         # Right Leg
              # 0.5, 0.5, 0.5, 0.5,      # Left Arm
              # 0.5, 0.5, 0.5, 0.5]      # Right Arm
              .2, .2, .2, .2,      # Left Arm
              .2, .2, .2, .2]      # Right Arm
    # weight:  [1, 1, 5, #2, 2, 5,  #15, 
    #       2, 2, 2,
    #       20, 20, 20, 20, 20,       # Left Leg
    #       20, 20, 20, 20, 20,         # Right Leg
    #       0.5, 0.5, 0.5, 0.5,      # Left Arm
    #       0.5, 0.5, 0.5, 0.5]      # Right Arm
    # weight:  [1, 1, 5, #2, 2, 5,  #15, 
    #       2, 2, 2,
    #       10, 10, 10, 10, 10,       # Left Leg
    #       10, 10, 10, 10, 10,         # Right Leg
    #       0.5, 0.5, 0.5, 0.5,      # Left Arm
    #       0.5, 0.5, 0.5, 0.5]      # Right Arm
  - type: VelocityTracking
    name: "VelocityTracking"
    weight: [4, 4, 2, #2, 2, 2, #3, 3, 3, #5, 
            # 5, 5, 5,
            2, 1, 2,
            0.05, 1, 1, 0.01, 0.1, #0.001,         # Left Leg
            0.05, 1, 1, 0.01, 0.1, #0.001,         # Right Leg
            .7, .7, .7, .7,
            .7, .7, .7, .7,]
            # 0.3, 0.3, 0.3, 0.3,      # Left Arm
            # 0.3, 0.3, 0.3, 0.3]      # Right Arm
  - type: TorqueRegularization
    name: "TorqueReg"
    weight: [0.001, 0.001, 0.001, 0.0001, 0.001, #0.001,            # Left Leg
            0.001, 0.001, 0.001, 0.0001, 0.001, #0.001,             # Right Leg
            0.01, 0.01, 0.01, 0.01,                           # Left Arm
            0.01, 0.01, 0.01, 0.01,]                          # Right Arm
  - type: ForceRegularization
    name: "ForceReg"
    # weight: [0.01, 0.01, 0.001]
    weight: [0.001, 0.001, 0.0001]
  - type: ForwardKinematics
    name: "left_toe_fk"
    frame: "left_toe"
    weight: [2, 2, 1]
  # - type: FootPolytope
  #   name: "left_toe_polytope"
  #   weight: [1, 1, 1, 1]
  #   frame: "left_toe"
  #   mu: 0.01
  #   delta: 0.01
  # - type: FootPolytope
  #   name: "left_heel_polytope"
  #   weight: [1, 1, 1, 1]
  #   frame: "left_heel"
  #   mu: 0.01
  #   delta: 0.01
  # - type: FootPolytope
  #   name: "right_toe_polytope"
  #   weight: [1, 1, 1, 1]
  #   frame: "right_toe"
  #   mu: 0.01
  #   delta: 0.01
  # - type: FootPolytope
  #   name: "right_heel_polytope"
  #   weight: [1, 1, 1, 1]
  #   frame: "right_heel"
  #   mu: 0.01
  #   delta: 0.01
contacts:
  # contact_frames: ["left_heel", "right_heel"]
  contact_frames: ["left_toe", "left_heel", "right_toe", "right_heel"]
  # hip_offsets: [-0.025, 0.1164, -0.025, -0.1164]
  hip_offsets: [0.145, 0.1164, -0.025, 0.1164, 0.145, -0.1164, -0.025, -0.1164]
  apex_height: 0.08
  apex_time: 0.75
  default_ground_height: 0
joint_defaults:
  joints: ["left_ankle_roll_joint", "right_ankle_roll_joint",
           "waist_yaw_joint", "waist_roll_joint", "waist_pitch_joint", 
           "left_wrist_roll_joint", "left_wrist_pitch_joint", "left_wrist_yaw_joint",
           "left_hand_thumb_0_joint", "left_hand_thumb_1_joint", "left_hand_thumb_2_joint",
           "left_hand_middle_0_joint", "left_hand_middle_1_joint",
           "left_hand_index_0_joint", "left_hand_index_1_joint",
           "right_wrist_roll_joint", "right_wrist_pitch_joint", "right_wrist_yaw_joint",
           "right_hand_thumb_0_joint", "right_hand_thumb_1_joint", "right_hand_thumb_2_joint",
           "right_hand_middle_0_joint", "right_hand_middle_1_joint",
           "right_hand_index_0_joint", "right_hand_index_1_joint",]
  values: [0, 0,
           0, 0, 0.03,
           0, 0, 0,
           0, 1, 1,
           0, 0,
           0, 0,
           0, 0, 0,
           0, -1, -1,
           0, 0,
           0, 0,]
line_search:
  alpha_min: 1e-3
  large_constraint_vio: 1e-2
  small_constraint_vio: 1e-6
  constraint_reduction_mult: 1e-6
  alpha_step: 0.5 # Since the line search is high variance, lowering this helps
  armijo_constant: 1e-4
targets:
  q_target: [0, 0, 0.74, #0.73, #0.77, #0.793, if the height is too high we get some singularity issues
              # 0, 0, 0.707106781, 0.707106781,
              0, 0, 0, 1,
             -0.5, 0, 0, 0.7, -0.216,
             -0.5, 0, 0, 0.7, -0.216,
             0, 0.27, 0, 0.9,
             0, -0.27, 0, 0.9]
  v_target: [0, 0, 0,
             0, 0, 0,
             0, 0, 0, 0, 0,
             0, 0, 0, 0, 0,
             0, 0, 0, 0,
             0, 0, 0, 0,]