general_settings:
  nodes: 32
  verbose: False #True
  node_dt_type: SmallFirst # Even, SmallFirst, Adaptive
  node_dt: 0.025 #0.025
  first_node_dt: 0.01 
  compile_derivatives: False #True
  base_frame: "pelvis"
  scale_cost: False
  max_initial_solves: 20
  initial_constraint_tol: 5e-4
  nodes_full_dynamics: 3 #3 #4   # Also determines how many nodes have torque constraints
  delay_prediction_dt: 0
  terminal_cost_weight: 10 #2 #10
solver_settings:
  rel_tol: 1e-3
  abs_tol: 1e-3
  verbose: False
  polish: False
  rho: 0.01
  alpha: 1.6 # 1.6, 1.1
  sigma: 1e-6
  adaptive_rho: False
  max_iter: 50 #50 #20 Increasing this definetly helps 40-60 seems like a good balance
  scaling: 10 # Solve gets faster as scaling goes down, but also the quality gets worse. There is a balance
constraints:
  friction_coef: 0.6 #0.7  # TODO: Tune this
  friction_margin: 2
  max_grf: 8000
  collisions:
    - frame1: "left_toe"
      frame2: "right_toe"
      radius1: 0.1 #0.13
      radius2: 0.1 #0.13
    - frame1: "left_heel"
      frame2: "right_heel"
      radius1: 0.1 #0.13
      radius2: 0.1 #0.13
    - frame1: "left_toe"
      frame2: "right_heel"
      radius1: 0.1
      radius2: 0.1
    - frame1: "left_heel"
      frame2: "right_toe"
      radius1: 0.1
      radius2: 0.1
    - frame1: "left_wrist_yaw_link"
      frame2: "waist_support_link"
      radius1: 0.06
      radius2: 0.06
    - frame1: "right_wrist_yaw_link"
      frame2: "waist_support_link"
      radius1: 0.06
      radius2: 0.06
costs:
# NOTE: The resulting behaviour is suprisingly sensitive
  - type: ConfigurationTracking
    name: "ConfigTracking"
    weight:  [2, 2, 5,  #15, 
              4, 4, 4,
          # 8, 8, 8,
          0.005, 3, 4, 0.0005, 1, #1,         # Left Leg
          0.005, 3, 4, 0.0005, 1, #1,         # Right Leg
          # 1, 1, 1,                  # Waist
          # 1, 1, 1, 1,      # Left Arm
          # 1, 1, 1, 1]      # Right Arm
          0.5, 0.5, 0.5, 0.5,      # Left Arm
          0.5, 0.5, 0.5, 0.5]      # Right Arm
  - type: VelocityTracking
    name: "VelocityTracking"
    weight: [2, 2, 2, #3, 3, 3, #5, 
            2, 1, 2,
            #5, 5, 5,
            0.005, 1, 2, 0.001, 0.1, #0.001,         # Left Leg
            0.005, 1, 2, 0.001, 0.1, #0.001,         # Right Leg
            # 1, 1, 1,                  # Waist
            0.3, 0.3, 0.3, 0.3,      # Left Arm
            0.3, 0.3, 0.3, 0.3]      # Right Arm
  - type: TorqueRegularization
    name: "TorqueReg"
    weight: [0.0001, 0.001, 0.001, 0.0001, 0.001, #0.001,            # Left Leg
            0.0001, 0.001, 0.001, 0.0001, 0.001, #0.001,             # Right Leg
            # 0.001, 0.001, 0.001,                                  # Waist
            0.01, 0.01, 0.01, 0.01,                           # Left Arm
            0.01, 0.01, 0.01, 0.01,]                          # Right Arm
  - type: ForceRegularization
    name: "ForceReg"
    # weight: [0.005, 0.005, 0.001]
    weight: [0.01, 0.01, 0.0001]
    # weight: [0.02, 0.02, 0.0002]
    # weight: [0.2, 0.2, 0.1]
contacts:
  # contact_frames: ["left_heel", "right_heel"]
  contact_frames: ["left_toe", "left_heel", "right_toe", "right_heel"]
  # hip_offsets: [-0.025, 0.1164, -0.025, -0.1164]
  hip_offsets: [0.145, 0.1164, -0.025, 0.1164, 0.145, -0.1164, -0.025, -0.1164]
joint_defaults:
  joints: ["left_ankle_roll_joint", "right_ankle_roll_joint",
           "waist_yaw_joint", "waist_roll_joint", "waist_pitch_joint", 
           "left_wrist_roll_joint", "left_wrist_pitch_joint", "left_wrist_yaw_joint",
           "left_hand_thumb_0_joint", "left_hand_thumb_1_joint", "left_hand_thumb_2_joint",
           "left_hand_middle_0_joint", "left_hand_middle_1_joint",
           "left_hand_index_0_joint", "left_hand_index_1_joint",
           "right_wrist_roll_joint", "right_wrist_pitch_joint", "right_wrist_yaw_joint",
           "right_hand_thumb_0_joint", "right_hand_thumb_1_joint", "right_hand_thumb_2_joint",
           "right_hand_middle_0_joint", "right_hand_middle_1_joint",
           "right_hand_index_0_joint", "right_hand_index_1_joint",]
  values: [0, 0,
           0, 0, 0.03,
           0, 0, 0,
           0, 1, 1,
           0, 0,
           0, 0,
           0, 0, 0,
           0, -1, -1,
           0, 0,
           0, 0,]
line_search:
  alpha_min: 1e-3
  large_constraint_vio: 1e-2
  small_constraint_vio: 1e-6
  constraint_reduction_mult: 1e-6
  alpha_step: 0.5 # Since the line search is high variance, lowering this helps
  armijo_constant: 1e-4