general_settings:
  nodes: 32
  verbose: True
  node_dt_type: SmallFirst # Even, SmallFirst, Adaptive
  node_dt: 0.025 #0.025
  first_node_dt: 0.01 # 0.01
  compile_derivatives: False #True
  base_frame: "torso"
  scale_cost: False
  max_initial_solves: 20
  initial_constraint_tol: 5e-4
  nodes_full_dynamics: 4 #4   # Also determines how many nodes have torque constraints
  delay_prediction_dt: 0 #-1e-2 #5e-3 # TODO: Tune or disable
  terminal_cost_weight: 1 #50 Having a smaller terminal weight seems to help for now
solver_settings:
  rel_tol: 1e-3
  abs_tol: 1e-3
  verbose: False
  polish: False
  rho: 0.05 #0.05 #0.05 looks good for no sim walking traj. 0.01 allows for standing
  alpha: 1.6 # 1.6, 1.1
  sigma: 1e-6 # 1e-10
  adaptive_rho: False
  max_iter: 20 #20 # TODO: Why does running this for more iterations with rho=0.1 make it so much worse? In general, why does rho=0.1 not work?
  scaling: 10
constraints:
  friction_coef: 0.5  # TODO: Tune this
  max_grf: 800
  collisions:
    - frame1: "FR_foot"
      frame2: "FL_foot"
      radius1: 0.06
      radius2: 0.06
    - frame1: "RR_foot"
      frame2: "RL_foot"
      radius1: 0.06
      radius2: 0.06
    - frame1: "FR_foot"
      frame2: "RR_foot"
      radius1: 0.06
      radius2: 0.06
    - frame1: "FL_foot"
      frame2: "RL_foot"
      radius1: 0.06
      radius2: 0.06
  # TODO: Add hand and knee collisions
costs:
  - type: ConfigurationTracking
    name: "ConfigTracking"
    weight:  [ 1.0, 1.0, 10.0,
          1.5, 1.5, 1.5,
          1, 1, 1,          # FL
          1, 1, 1,          # FR
          1, 1, 1,          # RL
          1, 1, 1]          # RR
  - type: VelocityTracking
    name: "VelocityTracking"
    weight: [1, 1, 5,
        .5, .5, .5,
        1, .1, 0.0,         # FL
        0.00, 0.05, 1,      # FR
        1, 1, 1,            # RL
        1, .1, 0.0]         # RR
  - type: TorqueRegularization
    name: "TorqueReg"
    weight: [.01, .01, .01,       # FL
             .01, .01, .01,       # FR
             .01, .01, .01,       # RL
             .01, .01, .01]       # RR
  - type: ForceRegularization
    name: "ForceReg"
    weight: [.0001, .0001, 0.01]
contacts:
  contact_frames: ["RL_foot", "FR_foot", "FL_foot", "RR_foot"]

line_search:
  alpha_min: 1e-3
  large_constraint_vio: 1e-2
  small_constraint_vio: 1e-6
  constraint_reduction_mult: 1e-6
  alpha_step: 0.5 # Since the line search is high variance, lowering this helps
  armijo_constant: 1e-4

  # Misc notes:
  # When rho = 0.1 I seem to follow the trajectory better (i.e. better open loop performance), but I have more oscillations and drift
  # When rho = 0.02 almost all of the drift and oscillations are removed but the open loop tracking is significantly worse.
  # In reality I think the better open loop performance is probably due to have better constraint satisfaction on the dynamics (but that needs confirmation)
  # Also unclear if it is just that the natural osciallations of the rho somehow help to stabilize