general_settings:
  nodes: 25 #32
  verbose: False #True
  node_dt_type: two_groups # Even, two_groups, Adaptive
  node_group_1_n: 5
  node_group_2_n: 20 #27
  node_dt_1: 0.015 #0.015 #0.015 
  node_dt_2: 0.035 #0.025
  compile_derivatives: False
  base_frame: "torso"
  scale_cost: False
  max_initial_solves: 20
  initial_constraint_tol: 5e-4
  nodes_full_dynamics: 24 #4 #10 #30 #10 #3 #4   # Also determines how many nodes have torque constraints
  delay_prediction_dt: 0
  terminal_cost_weight: 40 #2 #10
  log_file_name: "mpc_logs/go2_sim_mpc_log.csv"
solver_settings:
# HPIPM:
  mode: Speed #Balance #Balance #Balance #Speed #Robust #Balance -- To get a success the best chance is with Robust and give more iterations
  alpha_min: 1e-8
  max_iter: 10 #15 #20 #20 #14 #10 #15 #15 #10
  mu0: 10 #1 #20 #10 #100
  tol_stat: 1e-8 #1e-8
  tol_eq: 1e-8
  tol_comp: 1e-8 #1e-8
  tol_ineq: 1e-8
  reg_prim: 1e-12
  warm_start: 0
  pred_corr: 1 #1 #1 -- Setting this one seems to hurt the constraint violation across solves
  ric_alg: 1
  split_step: 0
constraints:
  friction_coef: 0.5 #0.7 #0.5  # TODO: Tune this
  friction_margin: 2
  max_grf: 250 #800
  min_grf: 10
  collisions:
    - frame1: "FR_foot"
      frame2: "FL_foot"
      radius1: 0.06
      radius2: 0.06
    - frame1: "RR_foot"
      frame2: "RL_foot"
      radius1: 0.06
      radius2: 0.06
    - frame1: "FR_foot"
      frame2: "RR_foot"
      radius1: 0.06
      radius2: 0.06
    - frame1: "FL_foot"
      frame2: "RL_foot"
      radius1: 0.06
      radius2: 0.06
  polytope_delta: 0.06 #0.04 #0.06
  polytope_shrinking_rad: 0.5 #0.2
  swing_start_node: 2 #3 # Note you want this set to 1 for all centroidal
  swing_end_node: 32
  holonomic_start_node: 1 #1 #1 # 2 #22 #2
  holonomic_end_node: 31 #32 #24 #32
  collision_start_node: 2
  collision_end_node: 32
  polytope_start_node: 2 #2 #2
  polytope_end_node: 32
  polytope_frames: ["RL_foot", "FR_foot", "FL_foot", "RR_foot"]
costs:
  - type: ConfigurationTracking
    name: "ConfigTracking"
    # weight:  [2.0, 2.0, 20, #2, 2, 150, or 2,2,30
    #       # 2, 2, 2,
    #       7, 7, 7,
    #       #25.5, 25.5, 25.5, # 5.5, 5.5, 5.5
    #       # Good walking, no reference:
    #       1, 1, .001,          # FL
    #       1, 1, .001,          # FR
    #       1, 1, .001,          # RL
    #       1, 1, .001,]          # RR
    # For ref generator:
    weight:  [10.0, 10.0, 20, #20, #2, 2, 150, or 2,2,30
      # 2, 2, 2,
      # 5, 5, 5,
      30, 30, 30,
      # 350.5, 350.5, 25.5, # 5.5, 5.5, 5.5
      # W/ ref:
      # .7, .7, .001,          # FL
      # .7, .7, .001,          # FR
      # .7, .7, .001,          # RL
      # .7, .7, .001,]          # RR
      # # W/o ref
      .1, .1, .001,          # FL
      .1, .1, .001,          # FR
      .1, .1, .001,          # RL
      .1, .1, .001,]          # RR
  - type: VelocityTracking
    name: "VelocityTracking"
    weight: [2, 2, 2, #5, #2, 2, 3,
        5, 5, 5,
        #15, 15, 15,
        0.2, 0.2, 0.0001,         # FL
        0.2, 0.2, 0.0001,         # FR
        0.2, 0.2, 0.0001,         # RL
        0.2, 0.2, 0.0001]         # RR
    # weight: [5, 5, 10, #2, 2, 3,
    #     # 5, 5, 5,
    #     1, 3, 3,
    #     0.02, 0.02, 0.01,         # FL
    #     0.02, 0.02, 0.01,         # FR
    #     0.02, 0.02, 0.01,         # RL
    #     0.02, 0.02, 0.01]         # RR
  - type: TorqueRegularization
    name: "TorqueReg"
    weight: [.0001, .0001, .0001,       # FL
             .0001, .0001, .0001,       # FR
             .0001, .0001, .0001,       # RL
             .0001, .0001, .0001]       # RR
  - type: ForceRegularization
    name: "ForceReg"
    # weight: [0.0001, 0.0001, 0.0001]
    weight: [0.001, 0.001, 0.001]

  # TODO: Why does removing this cause weird things with the MPC?
  - type: ForwardKinematics
    name: "FL_foot_fk"
    frame: "FL_foot"
    weight: [10,10,1] #[1, 1, 1] #TODO: Adding this has a minimal effect
  # - type: ForwardKinematics
  #   name: "FR_foot_fk"
  #   frame: "FR_foot"
  #   weight: [2, 2, 3]
  # - type: ForwardKinematics
  #   name: "RL_foot_fk"
  #   frame: "RL_foot"
  #   weight: [2, 2, 3]
  # - type: ForwardKinematics
  #   name: "RR_foot_fk"
  #   frame: "RR_foot"
  #   weight: [2, 2, 3]
  # ------------------------------ #
  # ----- Centroidal Weights ----- #
  # ------------------------------ #
  - type: CentroidalConfiguration
    name: "CentroidalConfig"
    weight:  [10.0, 10.0, 200, #20, #2, 2, 150, or 2,2,30
              # 2, 2, 2,
              # 5, 5, 5,
              # 10, 10, 10,
              350.5, 350.5, 25.5, # 5.5, 5.5, 5.5
              # W/ ref:
              # .7, .7, .001,          # FL
              # .7, .7, .001,          # FR
              # .7, .7, .001,          # RL
              # .7, .7, .001,]          # RR
              # # W/o ref
              .1, .1, .001,          # FL
              .1, .1, .001,          # FR
              .1, .1, .001,          # RL
              .1, .1, .001,]
  - type: CentroidalVelocity
    name: "CentroidalVel"
    weight:  [2, 2, 5, #2, 2, 3,
        # 5, 5, 5,
        15, 15, 15,
        0.1, 0.1, 0.0001,         # FL
        0.1, 0.1, 0.0001,         # FR
        0.1, 0.1, 0.0001,         # RL
        0.1, 0.1, 0.0001]         # RR
  - type: CentroidalForce
    name: "CentroidalForce"
    weight:  [0.0001, 0.0001, 0.0001]
    # TODO: Investigate this w/ no constraints. Weird stuff happening
  # - type: FootPolytope
  #   name: "FR_foot_polytope"
  #   weight: [1, 1, 1, 1]
  #   frame: "FR_foot"
  #   mu: 0.01
  #   delta: 0.005
  # - type: FootPolytope
  #   name: "FL_foot_polytope"
  #   weight: [1, 1, 1, 1]
  #   frame: "FL_foot"
  #   mu: 0.01
  #   delta: 0.005
  # - type: FootPolytope
  #   name: "RR_foot_polytope"
  #   weight: [1, 1, 1, 1]
  #   frame: "RR_foot"
  #   mu: 0.01
  #   delta: 0.005
  # - type: FootPolytope
  #   name: "RL_foot_polytope"
  #   weight: [1, 1, 1, 1]
  #   frame: "RL_foot"
  #   mu: 0.01
  #   delta: 0.005
contacts:
  contact_frames: ["RL_foot", "FR_foot", "FL_foot", "RR_foot"]
  # hip_offsets: [-0.1934, 0.142, 0.1734, -0.142, 0.1734, 0.142, -0.1934, -0.142]
  # hip_offsets: [-0.1934, 0.142, 0.2234, -0.142, 0.2234, 0.142, -0.1934, -0.142]
  hip_offsets: [-0.1934, 0.142, 0.2234, -0.142, 0.2234, 0.142, -0.1934, -0.142]
  apex_height: 0.08
  apex_time: 0.75
  default_ground_height: 0.01
line_search:
  alpha_min: 1e-3
  large_constraint_vio: 1e-2
  small_constraint_vio: 1e-6
  constraint_reduction_mult: 1e-6
  alpha_step: 0.5 # Since the line search is high variance, lowering this helps
  armijo_constant: 1e-4
targets:
  q_target: [0, 0, 0.28,
              0, 0, 0, 1,
              0, 0.9, -1.8,
              0, 0.9, -1.8,
              0, 0.9, -1.8,
              0, 0.9, -1.8]
  v_target: [0., 0.0, 0.,
              0, 0, 0,
              0, 0.0, 0.,
              0, 0.0, 0.,
              0, 0.0, 0.,
              0, 0.0, 0.]
wbc:
  base_weight: [20., 20, 20, 50, 50, 50]
  # base_weight: [1., 1, 1, 1, 1, 1]
  # base_weight: [200., 200, 200, 50, 50, 50]
  # [100., 100, 100, 100, 100, 100]
  # base_weight: [0., 0, 0, 0, 0, 0]
  joint_weight: [.01, .01, .01, .01, .01, .01, .01, .01, .01, .01, .01, .01]
  # joint_weight: [.1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1, .1]
  # joint_weight: [.0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0]
  # joint_weight: [10., 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
  # tau_weight: [.01, .01, .01, .01, .01, .01, .01, .01, .01, .01, .01, .01, .01, .01, .01, .01, .01, .01, .01]
  tau_weight: [.0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0]
  # force_weight: [0.0001, 0.0001, 0.001, 0.0001, 0.0001, 0.001, 0.0001, 0.0001, 0.001, 0.0001, 0.0001, 0.001]
  force_weight: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]
                #  0.0001, 0.0001, 0.001, 0.0001, 0.0001, 0.001, 0.0001, 0.0001, 0.001, 0.0001, 0.0001, 0.001]
  # kp: [750., 750, 750, 1550, 1550, 1550, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15]
  kp: [75., 75, 75, 100, 100, 100, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,]
  # kp: [75., 75, 75, 100, 100, 100, 750, 750, 750, 750, 750, 750, 750, 750, 750, 750, 750, 750, 750, 750, 750, 750, 750, 750, 750]
  # kp: [7500., 7500, 7500, 1550, 1550, 1550, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15]
  # kd: [10., 10, 10, 12, 12, 12, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, .2, 2, 2]
  kd: [20., 20, 20, 12, 12, 12, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
  # custom_torque_lims: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20]
  # custom_torque_lims: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
  # custom_torque_lims: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
  # custom_torque_lims: [10, 5, 5, 15, 7, 10, 5, 5, 15, 7, 1, 5, 5, 5, 5, 5, 5, 5, 5]
  verbose: False
  frame_tracking:
    - frame: "RL_foot"
      weight: [100, 100, 100]
      # weight: [0, 0, 0]
      kp: [1000, 1000, 1000]
      # kp: [500, 500, 500]
      kd: [15, 15, 15]
    - frame: "FR_foot"
      weight: [100, 100, 100]
      # weight: [0, 0, 0]
      kp: [1000, 1000, 1000]
      # kp: [500, 500, 500]
      kd: [15, 15, 15]
    - frame: "FL_foot"
      weight: [100, 100, 100]
      # weight: [0, 0, 0]
      kp: [1000, 1000, 1000]
      # kp: [500, 500, 500]
      kd: [15, 15, 15]
    - frame: "RR_foot"
      weight: [100, 100, 100]
      # weight: [0, 0, 0]
      kp: [1000, 1000, 1000]
      # kp: [500, 500, 500]
      kd: [15, 15, 15]
  skip_joints: []
  joint_values: []
  contact_frames: ["RL_foot", "FR_foot", "FL_foot", "RR_foot"]
  compile_derivs: False
  alpha: 0 #0.1 #0.001 #TODO: Tune
  log: True
  log_period: 5