general_settings:
  nodes: 32
  verbose: True
  node_dt: 0.025 
  compile_derivatives: True
  base_frame: "torso"
  scale_cost: False
  max_initial_solves: 20
  initial_constraint_tol: 5e-3
  nodes_full_dynamics: 2   # Also determines how many nodes have torque constraints
  integrate_velocity_targets: False
  delay_prediction_dt: 0 #-1e-2 #5e-3 # TODO: Tune or disable
  terminal_cost_weight: 5 #50 Having a smaller terminal weight seems to help for now
solver_settings:
  rel_tol: 1e-6
  abs_tol: 1e-6
  verbose: True
  polish: False
  # When rho = 0.1 I seem to follow the trajectory better (i.e. better open loop performance), but I have more oscillations and drift
  # When rho = 0.02 almost all of the drift and oscillations are removed but the open loop tracking is significantly worse.
  # In reality I think the better open loop performance is probably due to have better constraint satisfaction on the dynamics (but that needs confirmation)
  # Also unclear if it is just that the natural osciallations of the rho somehow help to stabilize
  rho: 0.01
  alpha: 1.6 # 1.6, 1.1
  sigma: 1e-6 # 1e-10
  adaptive_rho: False
  max_iter: 20
  scaling: 10
constraints:
  friction_coef: 0.5  # TODO: Tune this
  max_grf: 400
costs:
  - type: ConfigurationTracking
    name: "ConfigTracking"
    weight:  [ 0.0, 0.0, 10,  # Having x and y weights appears to be bad
              .01, .01, .01,
              0.01, 1, 0.001, 0.001, 0.1, 0.001, 0.001, 0.001, 0.001,
              0.01, 1, 0.001, 0.001, 0.1, 0.001, 0.001, 0.001, 0.001 ]
  - type: VelocityTracking
    name: "VelocityTracking"
    weight: [5, 2, 5,
            0.5, 0.5, 0.5,
            1, 1, 0.05, .002, .05, 4, 4, 4, 1,
            1, 1, 0.05, .002, .05, 4, 4, 4, 1]
  - type: TorqueRegularization
    name: "TorqueReg"
    weight: [.000, .000, .000, .000, .001, .5, .5, .5, .1,
            .000, .000, .000, .000, .001, .5, .5, .5, .1]
  - type: ForceRegularization
    name: "ForceReg"
    weight: [0.0001, 0.0001, 0.01]
  - type: ForwardKinematics
    name: "LeftToe"
    weight: [0.1, 0.1, 0.0]
    frame: "foot_front_left"
  - type: ForwardKinematics
    name: "LeftHeel"
    weight: [0.1, 0.1, 0.0]
    frame: "foot_rear_left"
  - type: ForwardKinematics
    name: "RightToe"
    weight: [0.1, 0.1, 0.0]
    frame: "foot_front_right"
  - type: ForwardKinematics
    name: "RightHeel"
    weight: [0.1, 0.1, 0.0]
    frame: "foot_rear_right"
contacts:
  # For now, removing hands
  # contact_frames: ["right_foot", "left_foot"] #, "right_hand", "left_hand"]
  contact_frames: ["foot_front_right", "foot_rear_right", "foot_front_left", "foot_rear_left"]

# Weights notes:
# - More weight on keeping the arm velocity and torques down since for now they are unconstrained
# - Slightly more weight on hip yaw torque to keep the feet straight

line_search:
  alpha_min: 1e-3
  large_constraint_vio: 1e-2
  small_constraint_vio: 1e-6
  constraint_reduction_mult: 1e-6
  alpha_step: 0.5 # Since the line search is high variance, lowering this helps
  armijo_constant: 1e-4